app = "crew-fireworks-staging"
org = "donnelly-development"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile.staging"

[env]
  PORT = "3000"
  NODE_ENV = "staging"
  VITE_API_BASE_URL = "https://crew-fireworks-api-staging.fly.dev/api"

[http_service]
  internal_port = 80
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
